//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourwebsiteFYP.DB_data_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FlightId { get; set; }
        public int PackageId { get; set; }
        public string AirlineName { get; set; }
        public string FlightClass { get; set; }
        public string Departure { get; set; }
        public string Arrival { get; set; }
        public decimal Price { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
