//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourwebsiteFYP.DB_data_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int GalleryId { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string Caption { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Product Product { get; set; }
    }
}
