//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourwebsiteFYP.DB_data_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.HotelImages = new HashSet<HotelImage>();
        }
    
        public int HotelId { get; set; }
        public string HotelName { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<decimal> PricePerNight { get; set; }
        public Nullable<int> PackageId { get; set; }
        public Nullable<int> MainImageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelImage> HotelImages { get; set; }
        public virtual HotelImage HotelImage { get; set; }
        public virtual Package Package { get; set; }
    }
}
