//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourwebsiteFYP.DB_data_models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageContent
    {
        public int Id { get; set; }
        public string PageName { get; set; }
        public string pageTitle { get; set; }
        public string pageSubtitle { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
